### ISSUE TITLE
servo turning

### ISSUE THREAD

**Issue by yousefg-codes** [automation-technology-club/Meccano-Smart-Servo#1]
whenever i use your for loop for the servo motion, it turns but then it turns back, so how do i fix this?

**Comment by kd8bxp** [comment]
It is suppose to do this. 
servo.setServoPosition(0,i);
will set the position of the servo you want to move, there are two for loops within the loop.  The first moves the direction in one way, the 2nd moves it back.
servo.setServoPosition(0,i);  the first number is the number of the servo to move starting at zero, the second number (i) is a number between 0 and 239 - this is the angle to move the servo to
This is just a test base code, it isn't suppose to do anything but move the servo in both directions. (Actually it's setup to move two servos in opposite directions of each other.)

**Comment by yousefg-codes** [comment]
no, i commented out the second loop which turns them back, but it still turns back (p.s. it does it slower than when it goes forward) i think it may be the circuitry?

**Comment by kd8bxp** [comment]
@yoyo7373 what version of the IDE are you using? I'll see if I can duplicate it. Do you have another servo to try ? Arduino UNO ? are you using the Arduino to power the servo? (could be a power issue, maybe)

**Comment by yousefg-codes** [comment]
1.8.7 is the version i am currently using

**Comment by yousefg-codes** [comment]
i tried it on multiple meccano servos and it does the same thing, and yes i am using the arduino to power it should i use an external power source?

**Comment by yousefg-codes** [comment]
I am using Arduino UNO

**Comment by kd8bxp** [comment]
I saw strange behavior on my 2nd servo when I removed the for statements..... I put a delay in before void loop() starts again, and that seemed to fix the issue.....

```
/* Meccano Arduino library required
 *  http://www.meccano.com/meccanoid-opensource
 *  
 *  Demo for 2 smart servos hooked delay(50);to pin 5.
 *  LeRoy Miller, 2017
 *  Feel Free to use this for whatever.
 */

#include "MeccaBrain.h"

MeccaBrain servo(5);
 
/*   setServoColor(int servoNum, byte color)  ->  sets the color of the Meccano Smart Servo module
The byte SERVONUM refers to the order of the servo in the chain.  The first servo plugged into your Arduino is 0.  
The next servo is 1.  The third servo is 2.   The last servo in a chain of 4 servos is 3.

The byte COLOR is a value  0xF0 - 0xF7 which has 8 possible colors (including all off and all on)
 0xF7  =  R, G,B – all On
 0xF6  =  G, B  - On;   R – Off
 0xF5  =  R, B  - On;   G – Off
 0xF4  =  B  - On;   R, G – Off
 0xF3  =  R,G – On;   B - Off
 0xF2  =  G  - On;   R, B – Off
 0xF1  =  R – On,   G, B – Off
 0xF0  =  R, G,B  – all Off

For example, if you want to set the servo at position 0 to Red and the servo at position 2 to Blue-Green, you would send the following two commands
setServoColor(0,0xF1)
setServoColor(2,0xF6)

setServoPosition(int servoNum, byte pos)  ->   sets a specific servo to a certain position 
The byte SERVONUM refers to the order of the servo in the chain.  The first servo plugged into your Arduino is 0.  
The next servo is 1.  The third servo is 2.   The last servo in a chain of 4 servos is 3.

The byte POS refers to the servo position  0x00 - 0xEF, which equals to a full 180 degree range.   
0x00 = full clockwise
0xEF = full counter clockwise
*/

//A STEP of 20 causes problems, it appears the servos need more power
#define STEP 1
/*This changes how fast the servo moves by changing how far it moves on each loop.
 * It has less to do with speed and more to do with position of the servo.
 * If you see weird issues, or your servos don't change color you probably
 * have a power issue.
 */

void setup() {
  // initialize serial communication:
  Serial.begin(9600);
 pinMode(5, OUTPUT);

 for (int i=0; i<51; i++) {
servo.communicate();
}
 
}
 
void loop(){
  servo.communicate();
  servo.setServoColor(0, 0xF4);
  servo.setServoColor(1, 0xF2);

servo.communicate();
    servo.setServoPosition(0,120);
    servo.setServoPosition(1, 239);

servo.communicate();
  servo.setServoColor(1, 0xF4);
  servo.setServoColor(0, 0xF2);
 
 
 delay(50);
}
```
so with two servos one will point to it's far point, the other will point at about the halfway point, the leds in the servos will flash. 
If you take the delay out, the 2nd servo will come around to about the 0 point and bounce quickly between 0 and about th 40 or 50 point, with the delay, it holds it position.
That's the closest I've gotten it to the problem you are having.
What I think is happening is "we" are asking it too communicate too fast inside the loop and it is confusing the servo, (at least that is what I think is happening)

**Comment by kd8bxp** [comment]
I think there is also a power issue, changing the sketch a little, and I've had my UNO reset a couple of times.... a external supply couldn't hurt, tie the ground of the external supply with the UNO ground, and I think between the delay, and the external supply that should fix the issue.... let me know.

**Comment by yousefg-codes** [comment]
i tried the external supply and adding the delay but it still goes back, and i found out that it's still in the for loop as it turns back (I used print statements to test this)

**Comment by kd8bxp** [comment]
Post your code, I haven't been able to duplicate what you are seeing.

**Comment by yousefg-codes** [comment]
for (int i=0; i<239; i = i+ STEP) {
    servo.communicate();
    servo.setServoPosition(0,i);
    servo.setServoPosition(1, 239 - i);
 }

**Comment by yousefg-codes** [comment]
/* Meccano Arduino library required
 *  http://www.meccano.com/meccanoid-opensource
 *  
 *  Demo for 2 smart servos hooked to pin 5.
 *  LeRoy Miller, 2017
 *  Feel Free to use this for whatever.
 */

#include "MeccaBrain.h"

MeccaBrain servo(4);
 
/*   setServoColor(int servoNum, byte color)  ->  sets the color of the Meccano Smart Servo module
The byte SERVONUM refers to the order of the servo in the chain.  The first servo plugged into your Arduino is 0.  
The next servo is 1.  The third servo is 2.   The last servo in a chain of 4 servos is 3.
The byte COLOR is a value  0xF0 - 0xF7 which has 8 possible colors (including all off and all on)
 0xF7  =  R, G,B – all On
 0xF6  =  G, B  - On;   R – Off
 0xF5  =  R, B  - On;   G – Off
 0xF4  =  B  - On;   R, G – Off
 0xF3  =  R,G – On;   B - Off
 0xF2  =  G  - On;   R, B – Off
 0xF1  =  R – On,   G, B – Off
 0xF0  =  R, G,B  – all Off
For example, if you want to set the servo at position 0 to Red and the servo at position 2 to Blue-Green, you would send the following two commands
setServoColor(0,0xF1)
setServoColor(2,0xF6)
setServoPosition(int servoNum, byte pos)  ->   sets a specific servo to a certain position 
The byte SERVONUM refers to the order of the servo in the chain.  The first servo plugged into your Arduino is 0.  
The next servo is 1.  The third servo is 2.   The last servo in a chain of 4 servos is 3.
The byte POS refers to the servo position  0x00 - 0xEF, which equals to a full 180 degree range.   
0x00 = full clockwise
0xEF = full counter clockwise
*/

//A STEP of 20 causes problems, it appears the servos need more power
#define STEP 1
/*This changes how fast the servo moves by changing how far it moves on each loop.
 * It has less to do with speed and more to do with position of the servo.
 * If you see weird issues, or your servos don't change color you probably
 * have a power issue.
 */

void setup() {
  // initialize serial communication:
  Serial.begin(9600);
 pinMode(4, OUTPUT);
 for(int i = 0; i<51; i+=STEP){
  servo.communicate();
 }
}

void loop(){
  servo.communicate();
  servo.setServoColor(0, 0xF4);
  servo.setServoColor(1, 0xF2);
  for (int i=0; i<239; i = i+ STEP) {
    servo.communicate();
    servo.setServoPosition(0,i);
    servo.setServoPosition(1, 239 - i);
 }
 Serial.println("Exited loop");
  delay(500);
servo.communicate();
  servo.setServoColor(1, 0xF4);
  servo.setServoColor(0, 0xF2);
  
 for (int i=239; i>0; i= i-STEP) {
  servo.communicate();
  servo.setServoPosition(0,i); 
  }
  Serial.println("Out of second loop");
  delay(500);
}
forget the last comment

**Comment by yousefg-codes** [comment]
Should i be adding any resistors to the circuit?

**Comment by kd8bxp** [comment]
It's doing what the code is telling it too do....
I'm not sure what you are trying to do, but it looks like it's doing what it should be doing to me.
you know everything in the loop() gets repeated correct(?)
So the first FOR statement has servo zero starting at the 0 point, and servo one starting at the 239 point,
on the 1st run though the 1st FOR statement the position of servo zero will be 239, and servo one will be 0. (It's also a little on the slow side because of the step)
The 2nd FOR statement is only moving servo zero, and it's slow because the step is slow.
It will take servo zero from the 239 position back to the zero position.
After the delay(500);
the loop repeats, but this time, Servo one is at the 239 position so it has to quickly go back to postion 239 when entering the 1st FOR statement, Servo zero is already at position zero, so it starts over again as normal.
The code is working as it is written, and the servos are doing what they should be doing. I can't duplicate any issues.
If this isn't what you want to do you'll have to write your own code to have it work the way you want. Sorry I don't think I can be any help here.

**Comment by kd8bxp** [comment]
Correction: after the delay Servo one is at the Zero position and quickly goes back to 239 when entering the 1st FOR statement.
